apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000
  selector:
    app: mongoexpress
  type: LoadBalancer