apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    app: mongoexpress
  type: LoadBalancer