---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akshello.vvvvv.ooo # This should be your domain name
  namespace: default
spec:
  secretName: akshello.vvvvv.ooo-tls # This will be your cert name in Kubernetes
  issuerRef:
    name: akshello-cert # This should match from 003-lets-encrypt.yaml
    kind: ClusterIssuer
  commonName: akshello.vvvvv.ooo # This is the main DNS name for the cert