---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: akshello-cert
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@vvvvv.ooo
    privateKeySecretRef:
      name: akshello-cert
    solvers:
    - http01:
        ingress:
          class: traefik